### ISSUE TITLE
news.ycombinator.com

### ISSUE THREAD

**Issue by nchapman** [mozilla/tippy-top-sites-deprecated#1]
![screen shot 2016-03-22 at 11 13 08 am](https://cloud.githubusercontent.com/assets/3095/13962638/1fbe0e22-f01f-11e5-86d3-c0ef70834c9e.png)

**Comment by pdehaan** [comment]
@nchapman What's the action on this?
You want me to add Hacker News to the data set and figure out the primary background color?

**Comment by pdehaan** [comment]
Ah, that's right... Embed.ly can't figure out how to get this favicon. I filed this as an upstream issue with them, but seems like it isn't fixed yet.

iframely can correctly parse the favicon: http://iframely.com/explore?uri=https%3A%2F%2Fnews.ycombinator.com%2F

As can clearbit: http://logo.clearbit.com/news.ycombinator.com

I can resize to a lovely 64x64px square image, but not sure if we want it transparent or not.
