### ISSUE TITLE
Gmail.com icon (mail.google.com)

### ISSUE THREAD

**Issue by nchapman** [mozilla/tippy-top-sites-deprecated#26]
We need a fancy Gmail icon. I don't have a bad example as I saw it on someone else's screen. Apologies.

**Comment by pdehaan** [comment]
Here's my screenshots, but it may be somewhat tainted by the fact I'm not logged into Google in this profile:

![new_tab_and_add_entry_for_gmail_com__mail_google_com__ _issue__26_ _nchapman_tippy-top-sites_and_add_entry_for_gmail_com__mail_google_com__ _issue__26_ _nchapman_tippy-top-sites](https://cloud.githubusercontent.com/assets/557895/14393219/89f5b200-fd7a-11e5-966c-9fd4f8f78b64.png)

And timeline view (which shows the URLs vs icons):
![activity_stream](https://cloud.githubusercontent.com/assets/557895/14393201/7182bb64-fd7a-11e5-93cd-599b171a06e6.png)

**Comment by pdehaan** [comment]
I reckon this was expertly fixed via @bryanbell's https://github.com/mozilla/tippy-top-sites/commit/f4ee860aee112696165df79244ea11d9b50d1f48 commit. Closing.
