### ISSUE TITLE
Formatting requests

### ISSUE THREAD

**Issue by k88hudson** [mozilla/tippy-top-sites-deprecated#3]
Would it be ok to:
- format colors as 8-bit (RGB) array (e.g. `[255, 255, 255]` instead of `#FFFFFF`). It just happens to sync up with embedly/makes calculations a bit easier (we don't have to do an extra conversion)
- remove `images/` from image urls (this is really easy to append but harder to parse out if we need to change the location of the images)

**Comment by k88hudson** [comment]
Happy to do a PR if you are ok with it :+1:

**Comment by nchapman** [comment]
@bryanbell wants to keep hex colors. We can absolutely remove the `images/` part of the path.

**Comment by bryanbell** [comment]
Can we write a converter for Hex to RGB? Getting RGB out of Photoshop is rather fussy.

**Comment by pdehaan** [comment]
@bryanbell absolutely, I can rebase #12 and convert the #RRGGBB to [RR, GG, BB] as an additional field, and then write some tests to make sure both values match (to prevent somebody from changing one value and not the other).

**Comment by pdehaan** [comment]
This should be fixed in #16.

**Comment by pdehaan** [comment]
Ref: #19

**Comment by pdehaan** [comment]
I think we found a workaround in #22 which should keep everybody happy. Closing [again].
